[project]
name = "news-telegram-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SobhanSaeedi7", email = "Sobi.S.K2007@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "feedparser>=6.0.14",
    "langchain>=1.4.3",
    "langchain-openai>=1.6.7",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
]

[project.scripts]
news-telegram-bot = "news_telegram_bot:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
